spring.application.name: employee-api
server.port: 8111

employee:
  api:
    port: 8112
    base-url: http://localhost:${employee.api.port}/api/v1/employee
    min-back-off-period: 30000
    max-attempts: 4